use Pizzeria;
DROP TABLE dinein;
DROP TABLE delivery;
DROP TABLE pickup;
DROP TABLE order_discount;
DROP TABLE pizza_discount;
DROP TABLE discount;
DROP TABLE pizza_topping;
DROP TABLE pizza;
DROP TABLE ordertable;
DROP TABLE customer;
DROP TABLE baseprice;
DROP TABLE topping;
DROP SCHEMA Pizzeria;